vutfitdiscord/rubbergod

- __main__.py
- config/config.template.py
- repository/roll_dice.py
Implements dice rolling - [Reference](https://wiki.roll20.net/Dice_Reference)
Only special features is Drop/Keep from the reference
This has not been properly tested locally through the bot, only via personal testing via inserting code
> Dice rolling first implementation

- __main__.py
- getDB.py
Added verify support for FEKT students
> Verify for FEKT

- __main__.py
- repository/karma.py
Not sure if I used karma_update function correctly on line 373. I tried to cover all bad inputs and exceptions but I might have missed some. The command is !karmagive USER NUMBER if the number is positive karma will be added if negative karma will be subtracted.
> Karma give command for admin

- __main__.py
- config/config.template.py
- repository/karma.py
Replaced strings "Role" "add-roles" "general" "Tohle funguje jen na VUT FIT serveru" "Hlasovani o karma ohodnoceni" for constants from config file
> Replacing strings with constants

- __main__.py
- config/config.template.py
Check line 526 where I changed condition. Added Arcas' ID to temp config so switch it to normal one.
> Arcas error when typing in PM

- __main__.py
- config/config.template.py
- repository/roll_dice.py
Reworks command parsing such that the prefix is now in the configuration file and running commands is more strict (!rollxyz will not be interpreted as !roll)
This also adds an args variable that commands can use that is the substring after the first space so the functions don't have to do it themselves in case they don't need anything else from the message object
> Rework command parsing

- __main__.py
- config/config.template.py
- repository/user.py
Resolves issue #24 
Also, this fixes a bug where the `User.has_role` static method returns False regardless of input
> Makes bot ignore bot messages

- README.md
- __main__.py
- repository/presence.py
- repository/utils.py
- requirements.txt
Resolves issue #12 
Note that this requires a pip package install
> Add Discord presence to bot

- repository/karma.py
added simple counter for emotes in one message
> message length fix in get_all

- config/config.template.py
- config/messages.py
- repository/base_repository.py
- repository/karma.py
- repository/reaction.py
- repository/rng.py
- repository/roll_dice.py
- repository/verification.py
- rubbergod.py
> Move all messages to a separate file

- features/karma.py
Fetch all the emojis at once instead of fetching one by one.
> Improve !karma get performance (maybe)

- config/messages.py
- rubbergod.py
Output looks like this:
```
Up since:  2019-08-03 19:30:50
Uptime:    0:00:05
```
> Nicer output on !uptime with added boottime

- features/karma.py
needed testing on VUT FIT discord
> leaderboards formating

- features/reaction.py
-Implemented role with spaces
-Added unicode emoji parser (should work for ZWJ emojis too)
> Modificated Role

- config/messages.py
- features/karma.py
- repository/karma_repo.py
- rubbergod.py
Some tests on server with more host should be fine.
Fixing #66
> ?karma output looks like ?karma stalk @me

- config/messages.py
- rubbergod.py
> send link on github when message is "PR"

- config/messages.py
- features/reaction.py
Send link to message, who wanted to pin it and channel where is message pinned
> added logging if bot pins message

- cogs/base.py
- cogs/karma.py
- cogs/meme.py
- cogs/random.py
- cogs/room_check.py
- cogs/verify.py
- config/config.template.py
- rubbergod.py
adding cogs, so now you can load which feature set you want to have. You can also unload feature, change it and back load without restarting bot.
resolving #68
> adding cogs

- cogs/meme.py
- config/config.template.py
Don't forget to config please.
> React on chain of emoticons from grillbot.

- features/reaction.py
> Role accept channels as well as roles

- cogs/review.py
- config/messages.py
- features/reaction.py
- features/review.py
- repository/database/review.py
- repository/review_repo.py
added option to remove review and remove reaction. Tier is now supported up to 4. Review now support up to 2000 chars (limited by discord message length). Commands are now easier and maybe more intuitive
> upgrade review feature

- features/reaction.py
Leo mě vyprokoval k tomuhle pull requestu; taky jsem do sebe dostal moc kofeinu a teď chci něco dělat v půl dvanáctý.
Bot neprovede pokus o pinnutí nepinovatelné zprávy a uživatele slušně upozorní, pokud se o to pokusí.
Nezkoušel jsem, jestli ta změna funguje, _baj d wej_.
> Bot neprovede pokus o pinnutí nepinovatelné zprávy

- cogs/review.py
- config/config.template.py
reviews now works again in DM and command check roles on server
> fixed dm reviews

- cogs/base.py
- config/config.template.py
- config/messages.py
@Toaster192 Treba ešte vymyslieť ako sa bude zadávať dátum a čas otvorenia.
(Prvý krát robím s pythonom a týmto botom, všetky rady sú vítané 😄 )
*ReBeL*
> Add kachna countdown

- README.md
- cogs/karma.py
- config/messages.py
- features/karma.py
- repository/karma_repo.py
New argument for leaderboard - offset where you want to start your leaderboard and then print 10 users from this position
> Leaderboard offset

- cogs/base.py
- config/config.template.py
- config/messages.py
(for holidays)
- Update kachna messages
> Add kachna temporary closed feature

- config/messages.py
Added newlines specified in issue #74.
> Issue #74 fix

- cogs/base.py
- cogs/kachna.py
- cogs/name_day.py
- config/config.template.py
- config/messages.py
* move kachna to separate class
> Add nameday command

- cogs/review.py
- config/messages.py
- features/reaction.py
- features/review.py
- logic/rng.py
small fix, if you added second review with uppercase subject shortcut new review was added instead of updating old one
> uppercase fix for review update

- cogs/fitwide.py
- config/config.template.py
- requirements.txt
Adds the `?find_rolehoarders` command, which finds people with suspiciously too many subject roles.
Also fixes the requirements.txt file which was missing the `requests` package
> find_rolehoarders command

- cogs/fitwide.py
- config/config.template.py
removes and adds a config value
> Add sorting to the rolehoarder command and a limit instead of treshold

- cogs/base.py
- cogs/week.py
- config/config.template.py
- logic/rng.py
* add week set feature for changing semesters
> #143 Move ?week to separate cog

- cogs/base.py
- config/config.template.py
- features/reaction.py
- repository/db_migrations.py
- rubbergod.py
- Added channels to configuration that will be ignored.
- Remove 📌 reactions as soon as message is pinned.
> Rubbergod improvements

- cogs/base.py
- config/app_config.py
- config/config.template.py
- features/karma.py
Link to corresponding page on Grillbot's leaderboard website, as suggested in #158
> Leaderboard link

- cogs/acl.py
- cogs/fitwide.py
- cogs/ios.py
- cogs/random.py
- cogs/review.py
- config/messages.py
- features/reaction.py
- features/verification.py
- logic/rng.py
- requirements.txt
- ?pick now accepts multi-word arguments, if they are enclosed in quotes (`?pick "first option" second third`).
- All strings in messages.py are in czech and have punctuation.
- All hardcodes strings have punctuation.
> Fix strings and improve ?pick command

- cogs/review.py
> add fit.nechutny statistics to zkratka command

- cogs/base.py
- cogs/review.py
- config/config.template.toml
- repository/review_repo.py
- rubbergod.py
resolves #94
Supporting all commands errors and event error.
Currently just `RawReactionActionEvent` is supported in events because I don't think we can get any other event in current setup.
> print ctx on error and review error fix

- cogs/error.py
ehm, error cog :HYPERS:
This was really meant to be in separate PR :smile:
> add error cog

- cogs/error.py
- cogs/warden.py
- utils.py
> fix timestamp for repost detection

- requirements.txt
- rubbergod.py
- Set discord.py version to 1.4.1
- Use AllowedMentions to only allow users, disallow @everyone or roles
> Bump to discord.py 1.4

- Dockerfile
- cogs/absolvent.py
- config/app_config.py
- config/config.template.toml
- config/messages.py
- repository/user_repo.py
- requirements.txt
Adding new command to verify diplomas which adds user honourable role
> Add absolvent cog

- cogs/absolvent.py
- cogs/review.py
- cogs/urban.py
- config/config.template.toml
- config/messages.py
Adding urban cog, so we can completely drop Mee6 bot.
PR also contains:
Fixed error on reviews.
Removing message on diploma verification and also removing "Droupout" role, as those people are not dropouts.
> Add urban cog + some improvements and bug fixes

- cogs/absolvent.py
- cogs/autopin.py
- cogs/config.py
- cogs/fitwide.py
- cogs/karma.py
- cogs/review.py
- cogs/roles.py
- cogs/system.py
- cogs/urban.py
- cogs/warden.py
- config/app_config.py
- config/config.template.toml
- config/messages.py
- features/verification.py
- rubbergod.py
- utils.py
Urban cog: fix error when no example was returned
Absolvent cog: add alias, so `?absolvent` invokes same command as `?diplom`
Review cog: fix help on `?subject update`, fixes #178 , NISY programme missing due to off by 1 error
After deploying please call `?subject update` to apply changes in subjects details
> Minor fixes

- cogs/warden.py
> Also count bot's reaction in repost duplicate limit

- cogs/karma.py
- cogs/review.py
- cogs/urban.py
- cogs/weather.py
- cogs/week.py
- features/karma.py
- utils.py
This should fix #197 
I couldn't reproduce this issue on local setup so TBH I am just guessing
> fix for subject types, review footer update

- cogs/review.py
> Fix embed creation

- cogs/meme.py
> Fix storno case insensitivity

- cogs/config.py
- config/messages.py
> Added regex parameter to ?config list command

- cogs/meme.py
- config/app_config.py
- config/config.template.toml
SSIA. A little bit of `black` formatting.
> Add delay to storno meme

- cogs/karma.py
- config/messages.py
- features/karma.py
- features/vote.py
Looks like bot was not updating results of vote after each reaction. I believe this was caused by my last PR to vote :(
> fix vote bot message updation

- cogs/roles.py
Now we can deny write pemission and user can't get it back by yourself... probably
> change just read permission

- features/menus/__init__.py
- features/menus/base.py
- features/menus/menu.py
- features/menus/source.py
- features/menus/util.py
- utils.py
> Implement discord.ext.menus

- cogs/hugs.py
- cogs/hugs/__init__.py
- cogs/hugs/hugs.py
- cogs/hugs/menus.py
- cogs/meme.py
- repository/database/hugs.py
- repository/db_migrations.py
- repository/hugs_repo.py
> Implement hug counting, hugboard

- cogs/autopin.py
- config/messages.py
- repository/database/pin_map.py
- repository/db_migrations.py
- repository/pin_repo.py
- utils.py
> Implemented auto pin reorder

- cogs/hugs/hugs.py
- utils.py
- Nicknames were ignored
- Invalid user names with ?hugs sent wrong response
- Reflect stalking in ?hugs title
- All emojis now get fetched from the base guild
> Fixed inconsistencies in hugs

- cogs/latex.py
- config/messages.py
> add latex eq cog

- cogs/latex.py
> send error on latex response not being an image

- cogs/ios.py
Replace fixed minutes format with possibility of conversion to higher time units
> IOS Time formating

- cogs/ios.py
Generalized strings in `cogs/ios.py` so they're not repeated multiple times.
Also changed some expressions and made them more pythonic.
Tested without database (obviously).
> Rewrite IOS cog

- README.md
- cogs/ios.py
- docker-compose.yml
> update python 3.7 -> 3.8

- cogs/acl.py
- cogs/base.py
- cogs/fitwide.py
- cogs/help.py
- cogs/hugs/hugs.py
- cogs/ios.py
- cogs/karma.py
- cogs/latex.py
- cogs/meme.py
- cogs/pet.py
- cogs/random.py
- cogs/review.py
- cogs/streamlinks.py
- cogs/urban.py
- cogs/verify.py
- cogs/vote.py
- cogs/week.py
- config/cooldowns.py
I hope I got every file correct. There's a lot of them.
I can't really test out all of them, but I hope I didn't make a copy-paste error.
left the guild-checked karma/getall command as it was
Resolves #57
> disable bot-room check in DMs, enable slash cmds in DMs, merge cmd cooldowns

- cogs/autopin.py
- cogs/config.py
- cogs/error.py
- config/app_config.py
- config/config.template.toml
> Resolve some issues

- cogs/subscriptions.py
- config/messages.py
- Missing arguments weren't being caught
- Command briefs weren't present
- Zero-length state wasn't being checked in "subscriptions" command
- Added command to display available channels
> Subscriptions: Apply fixes for found errors

- cogs/subscriptions.py
- rubbergod.py
DMs will only be sent in situations when the member is on the phone or completly offline.
This requires the Presence Intent to be enabled.
> Subscriptions: Limit notifications

- cogs/streamlinks.py
- config/messages.py
Check if there is date argument when there is no valid timestamp from video itself
> Add number of arguments check

- cogs/studijni.py
- config/messages.py
This should make our command more resistant to changes on faculty web page. If element cannot be found I just take all text and add it to the embed. Also adding support for some additional info such as currect changes in office hours
> make studijni command more resistant to changes on web

- cogs/meme_repost.py
- config/messages.py
Added check for already being reposted messages
Corrected format of reposted messages
> Meme repost fixes

- cogs/meme_repost.py
- repository/meme_repost_repo.py
And updated database format
Dont forget to drop old database table!
> Reworked meme reposting format

- cogs/fit_room.py
- cogs/meme_repost.py
And removed temporary fix for FIT room for building S and R
> [Meme repost] Hotfix - added checking of title length

- cogs/help.py
- cogs/meme.py
- config/app_config.py
- config/config.template.toml
- rubbergod.py
- utils.py
**Usage examples:**
- help for all commands:
```json
{
"method": "help",
"parameters": {
"user_id": "1234567890",
"command": "null"
}
}
```
or 
```json
{
"method": "help",
"parameters": {
"user_id": "1234567890",
}
}
```
- help for specific commands:
```json
{
"method": "help",
"parameters": {
"user_id": "1234567890",
"command": "reviews"
}
}
```
> Share help

- config/messages.py
Found more spelling mistakes and such.
Some messages lacked diacritics. - Not sure if intentionally.
> Fixed more grammatical mistakes, added diacritics

- cogs/grillbot_api.py
- cogs/help.py
- cogs/karma.py
- config/app_config.py
- config/config.template.toml
- repository/karma_repo.py
Query:
```json
{
"method": "Karma",
"parameters": {
"order": "asc",
"board": "karma",
"page": 1
}
}
```
Supported options:
order: asc, desc
board: karma, positive, negative
Response:
```json
{
"meta":{
"page":1,
"total_pages":1
},
"content":[
{
"positive":1,
"negative":0,
"member_ID":"180654870951493632",
"karma":0
},
{
"positive":0,
"negative":0,
"member_ID":"606523163563655169",
"karma":1
}
]
}
```
> extend grillbot api to karma

- cogs/meme_repost.py
Tested but here still can be bugs that I can't find without testing live
> [Meme Repost] Added reuploading of file attachments

- buttons/embed.py
- buttons/review.py
- cogs/grillbot_api.py
- cogs/help.py
- cogs/karma.py
- cogs/meme_repost.py
- cogs/reactions.py
- cogs/review.py
- cogs/streamlinks.py
- cogs/urban.py
- config/messages.py
- features/karma.py
- features/review.py
- rubbergod.py
- utils.py
> use interaction buttons for pagination

- cogs/karma.py
- cogs/pet.py
- requirements.txt
slash command error decorators now don't go through on_slash_command_error
> slash command errors

- rubbergod.py
using disnake lib but trying to use old discordpy logging
> change logging to disnake

- buttons/system.py
- cogs/reactions.py
- cogs/system.py
bookmark feature - lets users safe message with bookmark reaction and bot will send clickable link
> Change values in select for class names, add bookmark feature

- buttons/bookmark.py
- cogs/bookmark.py
- cogs/reactions.py
- config/config.template.toml
- config/messages.py
- modals/bookmark.py
Bookmark - users can react or use message command to save message in channel. Bot then sends it in DMs.
> Add bookmark feature

- buttons/embed.py
- buttons/review.py
- cogs/exams.py
- cogs/help.py
- cogs/hugs.py
- cogs/karma.py
- cogs/review.py
- cogs/streamlinks.py
- cogs/urban.py
- fix view timeout issue
- add better logging on view error
- add support for locking pagination, so just the user is able to change pages
> View improvements

- cogs/hugs.py
- cogs/karma.py
- features/leaderboard.py
After moving all commands to use the shared leaderboard formatted there were some issues with emojis:
- hugs were missing a method, that was replaced by direct utils call
- karma ishaboard was not using the correct emoji, from the emoji server but it was trying to find the emoji on the main server
> Emoji bug fixes

- buttons/system.py
- cogs/bookmark.py
- cogs/system.py
- features/bookmark.py
- modals/bookmark.py
- utils.py
Formatting for cogs if there are more so they split into multiple columns.
Bookmark now supports embeds, pictures, files and max length message.
> Cogs formatting, Bookmark multiple format support

- buttons/review.py
- cogs/subscriptions.py
> Subs default avatar fix

- cogs/error.py
- cogs/random.py
- features/error.py
- features/review.py
+ small fix for subject update
> Error logging fails on SQL exception

- buttons/bookmark.py
- cogs/bookmark.py
- config/messages.py
- features/bookmark.py
- modals/bookmark.py
bots have 8MB upload limit which limits files bot can send to DMs to users
> fix error on upload limit for bookmark

- cogs/error.py
- cogs/karma.py
- cogs/review.py
- cogs/roles.py
- config/messages.py
- utils.py
Override now as "create channel" shows progress bar and how many permissions it will write. 
When invoking command without permission it will print out "insufficient perms"
> Rewrite override to create channel, error handling

- cogs/roles.py
- config/messages.py
This will create a new role Adhoc if new permission is added or removed.
There is no need to update add-roles as this will be able to find a role with the the same name as the tagged channel.
> over 500 overwrites error fix

- cogs/help.py
- cogs/name_day.py
- features/git.py
- rubbergod.py
local time in nameday module
typos
remove commit hash from help command
> Use local time in nameday module

- cogs/review.py
- repository/review_repo.py
WTF command autocomplete now also has programmes
#406
> fix issue #406

- cogs/streamlinks.py
- features/prompt.py
- repository/stream_links_repo.py
streamlinks command as slash command
fixed issue when removing streamlink was not commited
> convert streamlink commands to slash

- .pre-commit-config.yaml
- README.md
- features/prompt.py
- requirements-dev.txt
- requirements.txt
> add type hint, add pre-commit for flake8

- cogs/fit_room.py
Also adding link for room to embed title
> Fix roomcheck for new api

- cogs/fit_room.py
New API contains the whole URL, not just relative part, replacement is not needed anymore
> Fix images for new api

- buttons/dynamic_verify.py
- features/dynamic_verify.py
- modals/dynamic_verify.py
- repository/database/verification.py
Roles were added to the user that clicked on submit button, not to the one who was targeted.
Adding removal of buttons after clicking on accept.
> Fix users in dynamic verify

- cogs/review.py
- config/messages.py
- features/review.py
- repository/review_repo.py
Added subcommand to list all subjects that were reviewed by user.
> Added list subcommand to reviews

- buttons/moderation.py
- cogs/moderation.py
- config/app_config.py
- config/config.template.toml
> info about mod tags

- buttons/moderation.py
- buttons/system.py
- cogs/fun.py
- cogs/moderation.py
- cogs/system.py
- features/bookmark.py
- features/karma.py
- features/review.py
add embed color, fix fact key issue
change style of buttons and embed, wording
Colour -> Color -- make occurence same across whole project
> Fix fact issue, Color occurence, Moderation GUI

- cogs/fun.py
- config/messages.py
adding new command yo mama joke
fix dadjoke missing return
> add yo mamajoke api, fix dadjoke

- cogs/name_day.py
- cogs/timeout.py
- config/messages.py
- repository/database/timeout.py
- repository/db_migrations.py
- repository/timeout_repo.py
- utils.py
I've added timeout feature that can timeout user indefinitely.
Basic unit of timeout is hour.
Name_day cog - get local zone from utils function, add header for bot owner
> Timeout feature

- buttons/system.py
- cogs/acl.py
- cogs/autopin.py
- cogs/bookmark.py
- cogs/config.py
- cogs/exams.py
- cogs/fitwide.py
- cogs/hugs.py
- cogs/ios.py
- cogs/karma.py
- cogs/name_day.py
- cogs/review.py
- cogs/roles.py
- cogs/streamlinks.py
- cogs/system.py
- cogs/timeout.py
- cogs/verify.py
- cogs/warden.py
- features/bookmark.py
- permissions/README.md
- permissions/permission_check.py
- permissions/room_check.py
- utils.py
create folder permissions
room_check and role_check
readme for folder
sticker is now supported in bookmark
> Move permission checks to seperate folder, Support sticker in bookmark

- buttons/system.py
- cogs/config.py
- cogs/error.py
- cogs/karma.py
- cogs/system.py
- cogs/warden.py
- config/messages.py
- permissions/permission_check.py
remove check failure, now global
add specific error message on failure
add timer to spamming
> Permissions rework again

- cogs/error.py
- cogs/verify.py
- config/app_config.py
- config/config.template.toml
> verify host

- Dockerfile
> Fix git not working in the container

- .gitignore
- cogs/reactions.py
- cogs/timeout_wars.py
- config/app_config.py
- config/config.template.toml
- config/messages.py
Let the timeout wars begin!
Use mute reaction to timeout users. Set config for timeout duration, immunity, percentage chance for modifiers and enjoy the battle royal.
> Implement timeout wars

- cogs/fitwide.py
- cogs/timeout.py
> Error catch, remove useless log on timeout

- cogs/hugs.py
- cogs/karma.py
- cogs/name_day.py
- cogs/random.py
- cogs/timeout.py
- config/messages.py
- features/karma.py
- permissions/README.md
- permissions/room_check.py
- repository/database/timeout.py
- repository/karma_repo.py
- repository/timeout_repo.py
- utils.py
> Create better room_check, rework karma commands, add start and length of timeout to embed

- cogs/timeout.py
0 time is in /timeout user now as "cancel"
> update users on listing

- rubbergod.py
> `system`: Ignore DC API Unavailable Error

- cogs/README.md
- cogs/ios.py
- config/app_config.py
- config/config.template.toml
- config/messages.py
> Rework `!ios` command to slash

- cogs/karma.py
- config/messages.py
- features/leaderboard.py
> hotfix leaderboard

- cogs/README.md
- cogs/forum.py
- config/app_config.py
- config/config.template.toml
> new cog "forum"

- cogs/error.py
- cogs/hugs.py
- cogs/karma.py
- cogs/pet.py
- cogs/random.py
- cogs/roles.py
- config/messages.py
- permissions/room_check.py
cleanup of errors, cooldowns, checks
> remove unnecessary error checks

- cogs/autopin.py
- cogs/hugs.py
- config/messages.py
some cleaning of pinning and autopin, also rewrite to slash
hug commands can be in multiple servers don't need for only main server
solve #509
> Rework autopin and pin commands

- cogs/autopin.py
- cogs/vote.py
- config/messages.py
- utils.py
> get or fetch channel

- cogs/README.md
- cogs/autopin.py
- cogs/fun.py
- config/messages.py
- features/autopin.py
add command `/pin get_all` for getting all pins from channel it supports markdown and json file
reorder messages
> add command `/pin get_all`

- cogs/autopin.py
- features/autopin.py
forum channel doesn't have pins
> hotfix `/pin get_all`

- cogs/error.py
- cogs/meme.py
- cogs/streamlinks.py
- config/app_config.py
- config/config.template.toml
- config/messages.py
- features/autopin.py
- features/review.py
- utils.py
- show images in markdown by default
- add discord timestamps
- ephemeral command on cooldown
- remove last covid mentions
- remove `??` and `???` command
> add discord timestamps, small tweaking

- cogs/memerepost.py
Fix negative karma not being properly counted
> `better-meme`: karma hotfix

- cogs/gif.py
See [issue](https://github.com/python-pillow/Pillow/issues/6115#issuecomment-1065810321). Credit @ Keizzha#0001.
> /bonk bg transparency fix

- docker-compose.yml
> Add `ssh_config` volume

- buttons/report.py
- cogs/README.md
- cogs/report.py
- config/config.template.toml
- config/messages.py
- requirements.txt
fix footer not hiding author of report
> add `/report google_form` and update sqlalchemy

- cogs/verify.py
> verify host send DM

- cogs/verify.py
- features/verification.py
Closes https://github.com/Toaster192/rubbergod/issues/635
> fix(verify): remove host roles only if verification code was sent

- buttons/base.py
- buttons/system.py
- cogs/absolvent.py
- cogs/autopin.py
- cogs/dynamicconfig.py
- cogs/error.py
- cogs/exams.py
- cogs/fitroom.py
- cogs/help.py
- cogs/hugs.py
- cogs/karma.py
- cogs/meme.py
- cogs/memerepost.py
- cogs/review.py
- cogs/roles.py
- cogs/streamlinks.py
- cogs/system.py
- cogs/verify.py
- cogs/vote.py
- cogs/warden.py
- config/messages.py
- features/bookmark.py
- features/callable_string.py
- features/dynamic_verify.py
- features/karma.py
- features/verification.py
- modals/bookmark.py
- modals/dynamic_verify.py
- utils.py
replaced fill_message utility function with callable string with foratting capabilities
> Messages upgrade

- cogs/system.py
- config/messages.py
- database/cooldown.py
- database/db_migrations.py
- database/error.py
- features/error.py
- utils.py
> add longest streak without error

- buttons/report.py
- cogs/autopin.py
- cogs/dynamicconfig.py
- cogs/error.py
- cogs/fitwide.py
- cogs/icons.py
- cogs/info.py
- cogs/karma.py
- cogs/moderation.py
- cogs/nameday.py
- cogs/report.py
- cogs/review.py
- cogs/timeout.py
- cogs/verify.py
- cogs/vote.py
- cogs/warden.py
- features/karma.py
- games/timeout_wars.py
- modals/report.py
- utils.py
- Weather now with f-strings
- Messages without format, since we have changed all strings to be callable we do not need a format fuction
- DynamicConfig: make path to config folder more clear, remove code repetition
> Small refactor

- cogs/review.py
Add option to for anonymous reviews. No need to be in Direct messages with bot.
> Add parameter for anonymous review

- buttons/embed.py
- buttons/review.py
Hopefully fix the issue with reviews pagination.
No related issues
> fix(review): fix error on pagination

- cogs/warden.py
Fix warden bug on out of index embeds.
None
> embeds out of range

- cogs/verify.py
> fix mention in verify host

- cogs/system.py
- config/messages.py
> add latency to `/uptime`

- modals/report.py
- requirements.txt
- utils.py
Adds parameter for the author in footer to be anonymous. Will be used in new Vote system and is now used in Report system
None
> add_author_footer() supports anonymous

- config/messages.py
- utils.py
Cooldown time was already in seconds and couldn't be cut more.
None
> fix `/icon` message formatting

- cogs/forum.py
Delete thread/post in channel inzerce if there are no messages.
> delete post if there are no messages

- README.md
> docu: Readme fix typo

- buttons/report.py
- database/report.py
Mods could send messages after report being resolved.
Now the report must be unresolved before they can again send messages.
Fixed a few typos in typing and added annotations.
None
> report sending answer after resolved

- buttons/subscription.py
- cogs/README.md
- cogs/subscriptions.py
- config/messages.py
- database/db_migrations.py
- database/subscription.py
Add new feature for subscription to forum channels based on tags.
> feat: add commands for forum subscriptions based on tags

- cogs/forum.py
fix error on guild is None when getting or fetching thread
> bug: fix error on guild_id is none None

- .flake8
- cogs/README.md
- cogs/roles.py
- config/messages.py
- add command for getting rooms with view_channel=True overwrite for users
- add command to change overwrites from users to role
> add overwrites management

- cogs/verify.py
> defer verify host

- cogs/fitwide.py
- cogs/forum.py
- config/messages.py
> rework role increments

- config/messages.py
argument typo in diplom command
Resolves #678
> argument typo

- cogs/fitwide.py
> missing message update

- cogs/README.md
- cogs/roles.py
- config/messages.py
add command that can resolve exclusive roles that users can't have both at the same time
> add command for removing role conflict

- cogs/README.md
- cogs/message.py
- config/config.template.toml
- config/messages.py
- modals/message.py
New feature enabling submod+ to send messages as bot. Should be used mostly to enable multi user editing of particular message.
None
> add message managment commands

- cogs/base.py
- cogs/error.py
- cogs/nameday.py
- cogs/roles.py
refactor check if user blocked bot
refactor check if InteractionTimedOut
> blocked DMs & InteractionTimedOut

- cogs/fitwide.py
SSIA
- Resolves #682 
Due to being only small edit and too much hassle of testing right now. This wasn't tested.
> deny send messages for @everyone

- cogs/error.py
> missing embed var

- buttons/general.py
- cogs/icons.py
- modals/report.py
found out, I gave wrong row to button in /icon
also fixed problem when report embed would keep delete button which would then make problems
None
> hotfix /icon wrong button row

- cogs/icons.py
- config/config.template.toml
> add defer to /icon

- cogs/grillbotapi.py
- cogs/karma.py
- config/app_config.py
- config/config.template.toml
- database/karma.py
- features/karma.py
This PR adds periodic synchronization of karma entities to the GrillBot instead of sending request in the commands (or events).
> Synchronize karma to GrillBot via periodic tasks.

- cogs/icons.py
using followup instead of send
none
> hotfix /icon follow up send

- cogs/icons.py
- config/config.template.toml
- config/messages.py
Add emoji to next to icon name in selects. Display emoji instead of name, where applicable.
> Rework icon select

- cogs/icons.py
> remove defer in /icon button

- cogs/timeout.py
- config/messages.py
> fix: wrong var for print

- buttons/embed.py
- buttons/review.py
Another attempt to fix the issue with Review views. If we fail to add a button for some reason, we try to recreate the whole view from scratch.
No changes in UI.
> fix(reviews): Recreate a view in case of button overflow

- cogs/system.py
> add defer to uptime

- cogs/fitwide.py
> fix missing var in fitwide

- cogs/fitwide.py
- database/verification.py
fix using delete on wrong object
add rooms for new 0bit/0mit roles
none
> wrong use of delete method in PermitDB

- cogs/README.md
- cogs/contestvote.py
- cogs/meme.py
- cogs/reactions.py
- config/app_config.py
- config/config.template.toml
- config/messages.py
Reuse vote module for contest where we want users to react to contribution and calculate the best one based on number of reactions and their value.
none
> Add contest vote module

- cogs/fitwide.py
> expect user instead of member

- buttons/contestvote.py
- buttons/report.py
- cogs/README.md
- cogs/contestvote.py
- config/app_config.py
- config/config.template.toml
- config/messages.py
- database/contestvote.py
- database/db_migrations.py
- add filtering, submissions are first sent to filter channel, then they can be sent to contest channel with button (see image)
- command `/get_author` of submission
- missed english phrase plus hinting in report
None
> Contest module

- database/contestvote.py
> fix get contribution author nonetype

- cogs/system.py
> add getting logs from journalctl

- modals/report.py
> missing await in modals/report

- cogs/system.py
we might need better server if getting logs takes more than 3 seconds. (aka fck this slow ass server omg)
> add defer to `/get_logs`

- buttons/poll.py
- cogs/error.py
- cogs/poll.py
- config/messages.py
- database/db_migrations.py
- database/poll.py
- features/poll.py
- permissions/custom_errors.py
- rubbergod.py
- utils.py
testing new poll on production for performance
> add testing boolean poll

- cogs/nameday.py
> disable mention with sending birthday information

- buttons/poll.py
- cogs/README.md
- cogs/error.py
- cogs/poll.py
- config/messages.py
- database/poll.py
- features/poll.py
- rubbergod.py
- utils.py
Rework `/poll boolean` and `/poll opinion`. Add task for it to close automatically. This is just a part to know how well it operates on production server.
Related issue #217
> Rework `/poll boolean` and `/poll opinion`

- docker-compose.yml
enables us to restart bot with /shutdown command. Now it restarts automatically, only the bot part!
> update compose for restarting bot

- buttons/poll.py
- cogs/poll.py
- config/messages.py
- database/poll.py
- features/poll.py
small update for polls 
- faster printing of voters
- fix shared cooldown on buttons
- other small fixes
- user gets notification on end of poll
- submod cant end others poll (stupid idea at the beginning)
> refactor poll views

- docker-compose.yml
without db restart, the bot wont run when restart occurs
> add restart for db service

- buttons/poll.py
- cogs/nameday.py
wrong use of allowed mentions + missing await
> fix nameday + missing await

- .gitignore
- cogs/system.py
- systemd/rubbergod-logging.service
[Optional] Are there any post deployment tasks we need to perform?
> Make `/get_logs` functional on Docker

- buttons/base.py
- buttons/error.py
- cogs/dynamicconfig.py
- cogs/error.py
- cogs/system.py
- database/__init__.py
- database/stats.py
- features/error.py
- rubbergod.py
Add better logging for errors, simplify logic regarding the error handling and follow DRY principle.
> refactor(error): add logging of errors

- .pre-commit-config.yaml
- cogs/error.py
- cogs/help.py
- cogs/memerepost.py
- cogs/roles.py
- config/messages.py
- features/error.py
- features/leaderboard.py
- features/review.py
- features/verify_helper.py
- utils.py
Small bug fixes for error handler including:
1. Reaction context Mocking - before errors from reactions would not be able to send messages when errors are ignored
2. Fix jump URL
3. Adding comments as discussed in my previous PR
4. Command not found error readded - I have removed responses to all messages for primary prefix
5. Traceback is not ephemeral
6. Blocked DMs handler outside of slash commands
I have also updated flake because version 6.0.0 complained about missing space after the colon in the URL. This also required some changes to isinstance instead of checking the type - E721
> fix(error): small fixes for our new error handler

- buttons/base.py
When handling button bug the message should have been edited and the error sent without error.
> fix error handling of buttons

- buttons/poll.py
- cogs/poll.py
- config/messages.py
- database/poll.py
- features/error.py
- features/poll.py
- utils.py
fix when closing polls to have the most up to date data
send message with embed that poll ended
> fix closing polls

- rubbergod.py
> add persistent view

- cogs/memerepost.py
- features/error.py
- fix broken link in error embed
- wrong use of isinstance on str
> fix broken link, wrong use of isinstance

- buttons/poll.py
- cogs/poll.py
- config/messages.py
- database/poll.py
- features/error.py
- features/poll.py
- Fix priting of poll title. It's unusable with formatting with discord. Channel names and emojis were problem.
- Percentage wasn't divided.
- Messages should be in dict if not skip it.
- missing `return True` in error handling
- Add cascade to delete.
- Fix printing in `/poll list` all messages are now ephemeral and is decided more precise if there are polls.
- I created a problem where every command would initialize a task and so updates would me more often than every 10s. Now it won't happen anymore.
> fix printing, percentage of votes, missing key in dict to update message

- features/poll.py
> polls wrong count of votes

- cogs/ios.py
- config/app_config.py
- config/config.template.toml
- features/list_message_sender.py
> Fix ios on Docker

- buttons/contestvote.py
- cogs/contestvote.py
- config/config.template.toml
- config/messages.py
add a manual command for approval when error happens with buttons
> add manual approve command

- cogs/fun.py
> Add defers to commands in `fun` cog

- setup/README.md
- setup/ssh_keygen.sh
- ssh_keygen.sh
- Add ssh key generation script
- Improve guide comment
- Add auto xlogin path generation
- Create new `setup` folder
- Update `ssh_keygen.sh`
- Add setup `README`
Some commands like `/ios` & `/verify_db pull` require a little more effort to set up. I've started writing up a documentation so the setup can be reproduced later on migration or dev setup by almost anyone.
> Add additional setup instructions

- Dockerfile
- setup/README.md
- setup/ssh_keygen.sh
- ssh_keygen.sh
> fix force push

- .gitignore
> Ignore temp files on production

- cogs/absolvent.py
- config/messages.py
- fix /diplom usable in DMs with bot
- change URL for diploms
None
> Fix /diplom command

- cogs/absolvent.py
- config/messages.py
update help message
missing parameter
> Fix \diplom command

- cogs/absolvent.py
- config/messages.py
> Update help messages for /diplom

- features/verification.py
> Fix other VUT faculties not verified automatically

- cogs/review.py
- database/review.py
autocomplete seems to be running slowly? we don't specifically know because it just takes too long to response might be server side issue with discord API. Still good to try.
> change autocomplete to use db

- config/messages.py
> Improve error message in `/tierboard`

- features/error.py
> typo in error

- cogs/fun.py
> fix yo-mamma api url

- features/error.py
get all failed `/diplom` commands to logging channel
> logging diplom error

- cogs/contestvote.py
- config/messages.py
- features/contestvote.py
Fix contest printing
- too many chars in the message
- using the command `/calculate contribution` on the wrong message
None
> fix contest printing

- cogs/contestvote.py
> missing argument in contest

- database/review.py
- features/error.py
This will fix the issue when the user wants to delete some reviews and it fails on SQL error because we were not deleting the votes for reviews correctly.
I have also added a small fix for error logging, now when we encounter an error we will rollback the transaction properly and still log the error both in DB and in bot-dev channel. This should make the bot more stable and DB error should not require restart anymore.
> Review fix

- .codespellrc
- .pre-commit-config.yaml
- buttons/embed.py
- cogs/absolvent.py
- cogs/dynamicconfig.py
- cogs/exams.py
- cogs/fitwide.py
- cogs/info.py
- cogs/memerepost.py
- cogs/review.py
- database/db_migrations.py
- database/karma.py
- features/autopin.py
- features/error.py
- features/karma.py
- permissions/README.md
Codespell should help us avoid spelling issues in the code. It is run with every commit as part of our pre-commit hooks.
Nothing
> Add Codespell pre-commit hook

- cogs/absolvent.py
- config/messages.py
Diplom command should now work as expected. I have also added better logging for users so they are aware of what is going on as the command can take a while. It was also useful during debugging.
> fix(absolvent): update xpaths for new thesis web page

- .github/workflows/main.yml
- .pre-commit-config.yaml
- cogs/system.py
update python version where we run testing
None
None
> update python testing version and pre-commit

- cogs/timeout.py
> fix showing author of timeout

- cogs/nameday.py
- cogs/timeout.py
- cogs/verify.py
- features/timeout.py
- rubbergod.py
- utils.py
Fix:
- verify wrong mention for error when bot is blocked
- fix datetime overflow with timeout forever
- fix typo in property name
- add grillbot API to `/timeout get_user`
- enable `/timeout get_user` to print user without timeouts (just for other info)
- change getting bot.owner_id
Resolve #818
> fix:Timeout & Verify

- features/timeout.py
> raise ApiError typo

- cogs/timeout.py
- config/messages.py
- database/timeout.py
- features/timeout.py
forgot that you can't fetch automod user
remove support of adding timeout length 0
fix wrong mod in /timeout_list
none
> timeout fix nonetype user

- features/verify_helper.py
fix using strip on None
resolves #829
> fix /verify strip on None

- features/verify_helper.py
Verify without login now results in correct data in DB.
- fix for #832
> fix(verify): users without login now can verify

- cogs/autopin.py
slash command `/pin_mod` visible only in guilds
none
> guild only `/pin_mod`

- cogs/fitwide.py
- config/messages.py
vutapi command to return plain json from vut API. This can be useful in debugging.
> feat: add vutapi command

- cogs/emoji/__init__.py
- cogs/emoji/cog.py
- cogs/emoji/messages_cz.py
- config/messages.py
Migrate Emoji cog to folder
- Resolves #855
> migrate Emoji to folder

- cogs/emoji/cog.py
- cogs/emoji/messages_cz.py
> fix emoji messages

- cogs/timeout.py
Fix printing of timeout. Time was in UTC, now it is in local zone.
none
> fix timeout print

- cogs/week/__init__.py
- cogs/week/cog.py
- cogs/week/messages_cz.py
- config/messages.py
> refactor(week): move week cog to folder

- cogs/poll/__init__.py
- cogs/poll/cog.py
- cogs/poll/features.py
- cogs/poll/messages_cz.py
- cogs/poll/views.py
- config/config.template.toml
- config/messages.py
- rubbergod.py
Migrate poll cog to folder
- Resolves #876
> move poll to folder

- cogs/streamlinks/__init__.py
- cogs/streamlinks/cog.py
- cogs/streamlinks/messages_cz.py
- config/messages.py
> refactor(streamlinks): move to subfolder

- cogs/studijni/__init__.py
- cogs/studijni/cog.py
- cogs/studijni/messages_cz.py
- config/messages.py
> refactor(studijni): move studijni to subfolder

- cogs/fitroom/__init__.py
- cogs/fitroom/cog.py
- cogs/fitroom/messages_cz.py
- config/messages.py
None
Closes https://github.com/vutfitdiscord/rubbergod/issues/858
> refator(fitroom): move fitroom to a subfolder

- cogs/random/__init__.py
- cogs/random/cog.py
- cogs/random/messages_cz.py
- config/messages.py
None
Closes https://github.com/vutfitdiscord/rubbergod/issues/877
> refactor(random): move random cog to a subfolder

- cogs/gif/__init__.py
- cogs/gif/cog.py
- cogs/gif/messages_cz.py
- config/messages.py
> migrate gif to folder

- cogs/nameday/__init__.py
- cogs/nameday/cog.py
- cogs/nameday/messages_cz.py
- config/messages.py
> migrate nameday to folder

- cogs/help/__init__.py
- cogs/help/cog.py
- cogs/help/messages_cz.py
- config/messages.py
> migrate help to folder

- cogs/reactions/__init__.py
- cogs/reactions/cog.py
- cogs/reactions/messages_cz.py
> migrate reactions to folder

- cogs/forum/__init__.py
- cogs/forum/cog.py
- cogs/forum/messages_cz.py
> migrate forum to folder

- cogs/subscriptions/__init__.py
- cogs/subscriptions/cog.py
- cogs/subscriptions/messages_cz.py
- config/messages.py
> migrate subscription to folder

- cogs/hugs/__init__.py
- cogs/hugs/cog.py
- cogs/hugs/messages_cz.py
- config/config.template.toml
- config/messages.py
> migrate hugs to folder

- cogs/info/__init__.py
- cogs/info/cog.py
- cogs/info/messages_cz.py
- config/messages.py
> migrate info to folder

- cogs/latex/__init__.py
- cogs/latex/cog.py
- cogs/latex/messages_cz.py
- config/messages.py
> migrate latex to folder

- cogs/timeout/__init__.py
- cogs/timeout/cog.py
- cogs/timeout/features.py
- cogs/timeout/messages_cz.py
- config/messages.py
> migrate timeout to folder

- cogs/message/__init__.py
- cogs/message/cog.py
- cogs/message/messages_cz.py
- cogs/message/modals.py
- config/messages.py
> migrate message to folder

- cogs/icons/__init__.py
- cogs/icons/cog.py
- cogs/icons/features.py
- cogs/icons/messages_cz.py
- cogs/icons/views.py
- config/messages.py
> migrate icons to folder

- cogs/moderation/__init__.py
- cogs/moderation/cog.py
- cogs/moderation/features.py
- cogs/moderation/messages_cz.py
- cogs/moderation/views.py
- config/messages.py
> migrate moderation to folder

- cogs/autopin/__init__.py
- cogs/autopin/cog.py
- cogs/autopin/features.py
- cogs/autopin/messages_cz.py
- config/messages.py
> Migrate Autopin to folder

- cogs/absolvent/__init__.py
- cogs/absolvent/cog.py
- cogs/absolvent/messages_cz.py
- config/messages.py
> migrate absolvent to folder

- cogs/autopin/cog.py
- cogs/bookmark/__init__.py
- cogs/bookmark/cog.py
- cogs/contestvote/__init__.py
- cogs/emoji/__init__.py
- cogs/emoji/cog.py
- cogs/fitroom/cog.py
- cogs/forum/cog.py
- cogs/fun/cog.py
- cogs/gif/cog.py
- cogs/grillbotapi/cog.py
- cogs/hugs/cog.py
- cogs/info/cog.py
- cogs/latex/cog.py
- cogs/meme/cog.py
- cogs/message/cog.py
- cogs/moderation/cog.py
- cogs/nameday/cog.py
- cogs/random/cog.py
- cogs/reactions/cog.py
- cogs/streamlinks/cog.py
- cogs/studijni/cog.py
- cogs/week/cog.py
> fix missing typing

- cogs/contestvote/cog.py
- cogs/contestvote/features.py
remove self from function
none
> refactor contestvote cog

- cogs/moderation/cog.py
- cogs/moderation/features.py
Refactor inheriting self parameter in functions
None
> refactor moderation cog

- docker-compose.yml
deprecated parameter
https://docs.docker.com/compose/compose-file/compose-versioning/
None
> deprecated version

- cogs/report/features.py
- cogs/report/modals.py
- cogs/report/views.py
remove passing self in function
none
> refactor report cog

- cogs/timeout/cog.py
- cogs/timeout/features.py
add listing users that are no longer in guild
remove paramater self
none
> refactor timeout cog

- .pre-commit-config.yaml
- cogs/karma/__init__.py
- cogs/karma/cog.py
- cogs/karma/features.py
- cogs/karma/messages_cz.py
- cogs/memerepost.py
- config/messages.py
- pyproject.toml
> Migrate karma to folder

- cogs/system/features.py
> add comment

- cogs/exams/__init__.py
- cogs/exams/cog.py
- cogs/exams/features.py
- cogs/exams/messages_cz.py
- config/messages.py
> refactor(exams): move exams to a separate folder

- cogs/bettermeme/__init__.py
- cogs/bettermeme/cog.py
- cogs/bettermeme/messages_cz.py
- config/config.template.toml
- config/messages.py
- database/better_meme.py
> Migrate Memerepost and rename to Bettermeme

- cogs/vote/__init__.py
- cogs/vote/cog.py
- cogs/vote/features.py
- cogs/vote/messages_cz.py
- config/messages.py
> Migrate vote to folder

- cogs/warden/__init__.py
- cogs/warden/cog.py
- cogs/warden/features.py
- cogs/warden/messages_cz.py
- config/messages.py
> migrate warden to folder

- .github/workflows/main.yml
- .pre-commit-config.yaml
- buttons/embed.py
- cogs/base.py
- cogs/exams/features.py
- cogs/gif/features.py
- cogs/karma/features.py
- cogs/review/cog.py
- cogs/review/features.py
- cogs/review/views.py
- database/cooldown.py
- database/error.py
- database/exams.py
- database/karma.py
- database/review.py
- database/stats.py
- features/callable_string.py
- features/error.py
- features/leaderboard.py
- features/sports.py
- features/table_generator.py
- other/getDB.py
- other/getDifference.py
- pyproject.toml
- utils.py
Add MyPy to CI. I could not make it fully work with our CallableString, so we skipped the operator check because it was not working as expected for us. I have also fixed the pre-commit in GH Actions. It is not being run on all files but only on those changed in the PR.
Please note that I haven't fixed all errors from MyPy and I am not sure if I will do that. It is a LOT of issues, like 400 and it is not easy to define types for all of those. I would suggest switching to an approach where we fix those files once we update them.
> Mypy check

- cogs/exams/cog.py
- cogs/exams/features.py
When moving cog to separate folder and splitting it into features file and cog file I somehow forgot the exams command in the feature file.
No issues
> fix(exams): fix exams command

- cogs/timeoutwars.py
Check for messages older than 1 day and skip them
printing reason in embed
none
> Timeoutwars

- cogs/error/__init__.py
- cogs/error/cog.py
- cogs/error/messages_cz.py
> migrate error to folder

- cogs/README.md
- cogs/contestvote/cog.py
- cogs/fitroom/cog.py
- cogs/icons/cog.py
- cogs/icons/messages_cz.py
- cogs/verify/cog.py
> Update readme & last fixes

- cogs/bettermeme/cog.py
- cogs/fitwide/cog.py
- cogs/help/cog.py
- cogs/icons/cog.py
- cogs/icons/features.py
- cogs/moderation/features.py
- cogs/poll/cog.py
- cogs/poll/features.py
- cogs/report/cog.py
- cogs/warden/cog.py
- database/better_meme.py
- database/contestvote.py
- database/hugs.py
- database/image.py
- database/meme_repost.py
- database/pin_map.py
- database/poll.py
- database/report.py
- database/streamlinks.py
- database/subscription.py
- database/timeout.py
- database/verification.py
- database/vote.py
- rubbergod.py
Fix some of mypy issues - cca 200 to go
- Related #952
> fix: fix mypy issues

- cogs/timeout/cog.py
- cogs/timeout/features.py
- database/report.py
fix mypy issues
fix listing spam reports
none
> mypy fix: timeout

- cogs/roles/cog.py
- database/year_increment.py
> Mypy fix for roles module

- cogs/random/cog.py
> mypy fix: random

- cogs/system/features.py
- cogs/system/views.py
> mypy fix: system

- cogs/report/features.py
- cogs/report/features_errors.py
- cogs/report/messages_cz.py
- cogs/report/modals.py
- cogs/report/views.py
- database/report.py
Mypy fixes for report module
None
> mypy fix:report

- cogs/message/modals.py
> mypy fix: message

- cogs/streamlinks/cog.py
- database/review.py
- database/streamlinks.py
I had one issue with requests.urllib3 and it was not working even with typeshed so I decided to simply ignore the error. It is not that important
> Streamlinks mypy

- cogs/absolvent/cog.py
> mypy fix: absolvent

- cogs/fun/cog.py
> mypy fix: fun

- .gitignore
- cogs/bettermeme/cog.py
- cogs/karma/cog.py
- cogs/reactions/cog.py
- config/app_config.py
- config/config.template.toml
- database/meme_repost.py
forgot to update names for beterrmeme config
none
> update config names

- cogs/ios/features.py
> fix(ios): fix mypy issues

- cogs/bettermeme/cog.py
- cogs/reactions/cog.py
bettermeme wasn't in reaction cog
none
> fix rename of bettermeme

- cogs/icons/views.py
wrong var names for messages
none
> fix wrong message vars

- cogs/README.md
- cogs/help/cog.py
- cogs/system/cog.py
- cogs/system/messages_cz.py
- cogs/verify/features_dynamic_verify.py
- config/messages.py
- features/verification.py
- add new command `/rubbergod` with basic info
- uniform colour for yellow
- Resolves #779
> Add `/rubbergod` command

- cogs/report/modals.py
- cogs/report/views.py
when removing message with delete button in reports it raised exception instead of only sending phrase
none
> fix delete missing message

- setup/README.md
- setup/leakcheck/leakcheck
- setup/leakcheck/leakcheck-eva
- setup/leakcheck/leakcheck-merlin
for the ability to set up `/ios` command from scratch somewhere in the future
> Add leakcheck scripts from merlin

- cogs/info/cog.py
- cogs/info/messages_cz.py
Use messages for weather
- Resolves #use messages #577
> use messages in info

- cogs/fitwide/features.py
- cogs/fitwide/messages_cz.py
> Change teacher listing format

- cogs/fitwide/cog.py
> fix: limit none on teacher info purge

- cogs/README.md
- cogs/fitwide/cog.py
- cogs/fitwide/features.py
> Update cog README, fix empty listing bug

- config/app_config.py
Make config a singleton class with an instance attribute that will store the one shared instance
> feat: make config singleton

- cogs/ios/features.py
> fix: ios hotfix

- cogs/ios/features.py
> fix: Anotha ios hotfix

- cogs/ios/features.py
- cogs/ios/messages_cz.py
> feat: Improve error messages, remove public shaming

- cogs/ios/features.py
- setup/leakcheck/leakcheck-merlin
> docs: Add fixed `leakcheck` to `setup/`

- cogs/timeout/cog.py
- cogs/timeout/features.py
- cogs/timeout/messages_cz.py
- database/timeout.py
Add grillbot API for timeout so we have timeouts in web view
none
> add grillbot endpoint for timeouts

- cogs/ios/cog.py
- cogs/ios/messages_cz.py
- setup/ssh_keygen.sh
> feat(ios): Treat ssh connection errors specially

- cogs/timeout/features.py
sending selftimeouts to grillbot is not wanted
none
> fix: sending selftimeout

- database/README.md
- database/db_migrations.py
- rubbergod.py
Add documentation update how to backup database and restore it. I have tried using sqlalchemy to do it but was not successful.
Remove deprecated arguments.
- related #993
> update readme for database backup and arguments

- cogs/system/cog.py
- database/error.py
if there is no log of bug in database the last_error is None and throws error
none
> nonetype last_error

- README.md
which GitHub supports, see: https://github.com/orgs/community/discussions/16925
> Use nice and shiny markdown alerts

- .gitignore
> remove tracking of backup.sql

- cogs/gif/cog.py
> fix gif wrong author

- .github/holopin.yml
add holopin automation for badges, needs holopin bot added, waiting for @Toaster192
none
> add holopin automation for badges

- cogs/timeout/features.py
> wrong send method

- cogs/message/cog.py
- cogs/message/messages_cz.py
- cogs/message/modals.py
Add sending/resending messages with attachments
- removed unneccessary check for messageNotFound
none
> add sending/resending messages with attachments

- cogs/timeout/cog.py
> fix: invalid phrase

- cogs/report/modals.py
- cogs/timeout/cog.py
- cogs/timeout/features.py
- utils.py
- Listing user timeouts on report
- Parametrize limit in parsing attachments
none
> Listing user timeouts on report

- features/verify_helper.py
Just set the "rok_studia" to 0 when saving a new person with `"rok_studia"==1`.
Just so we don't have 0bit and 1bit mixed together for the summer
> Add temporary workaround for 0BIT support

- features/verification.py
> make "r" in year optional

- cogs/fitwide/cog.py
- cogs/fitwide/features.py
> fix: Don't send update log when nothing changed

- README.md
- docker-compose.yml
- logs/README.md
Add readme for permissions for logs.
none
> Add readme for logs

- cogs/message/cog.py
- cogs/message/modals.py
- fix sending message without attachment
- enable sending only attachment (previously returned 404 error)
none
> Fix Message module and add feature

- .github/workflows/deployment.yml
- .github/workflows/lint.yml
- deployment.sh
Enable deploying via github actions
- Resolves #1013
> add deployment workflow

- cogs/help/cog.py
- cogs/karma/cog.py
- cogs/review/features.py
- cogs/streamlinks/cog.py
- cogs/timeout/features.py
- features/error.py
- utils.py
- Use built-in timestamp creator
- Remove unused functions
- Add type hints for most functions
Resolves - https://github.com/vutfitdiscord/rubbergod/issues/755
> Utils update

- .github/workflows/deployment.yml
- .github/workflows/lint.yml
- deployment.sh
- docker-compose.yml
Use pre-commit ci for lint checking.
Fixes problem of failing lint when deploying because there is no PR ref.
With this we have now automatic deploy via github.
Do we want to make packages public? If so we need to update dockerfile with label.
None
> Update deployment workflow

- .github/workflows/deployment.yml
> fix typo in deployment.yml directory

- utils.py
Sometimes discord API returns nonetype when there's user
None
> check for nonetype author

- features/error.py
Send errors associated with /verify command to logging channel only.
- Resolves #1060
> logging verify error

- README.md
Update config line numbers for text channels in setup section.
none
none
> update line numbers

- README.md
This one particular line is a little bit confusing IMO, so I went and fixed it
> docs: Update/fix confusing command sync tip

- features/verify_helper.py
fix accessing wrong key in data.json from vut api
none
> fix verify for fit employees

- cogs/nameday/cog.py
- cogs/nameday/messages_cz.py
Use global sessions for API requests.
none
> use sessions in nameday cog

- buttons/embed.py
- cogs/review/cog.py
- cogs/review/features.py
- cogs/review/views.py
- utils/__init__.py
- utils/colors.py
This is 1st part of a refactor for review system. This updates
- subclassing disnake.Color to have our custom colors making it more universal
- some small nitpicks like documentation
- updating View name to ReviewView
none
> Review refactor | Part 1

- utils/__init__.py
Small refactor to avoid noqa comments
No issues
> refactor: add __all__ section to utils

- cogs/studijni/cog.py
> studijni: remove requests, use global session

- cogs/fitroom/cog.py
- cogs/fitroom/messages_cz.py
> fitroom: remove requests, use global session

- cogs/autopin/cog.py
- cogs/contestvote/cog.py
- cogs/emoji/cog.py
- cogs/exams/cog.py
- cogs/fitroom/cog.py
- cogs/fitwide/cog.py
- cogs/fun/cog.py
- cogs/gif/cog.py
- cogs/help/cog.py
- cogs/hugs/cog.py
- cogs/info/cog.py
- cogs/ios/cog.py
- cogs/karma/cog.py
- cogs/latex/cog.py
- cogs/message/cog.py
- cogs/random/cog.py
- cogs/report/cog.py
- cogs/review/cog.py
- cogs/streamlinks/cog.py
- cogs/subscriptions/cog.py
- cogs/system/cog.py
- cogs/timeout/cog.py
- cogs/verify/cog.py
- cogs/week/cog.py
- utils/__init__.py
- utils/cooldowns.py
> move cooldowns to utils

- buttons/error.py
Fix exception when trying to get traceback on an error message where embed is missing (was removed manually by someone).
- Resolves #828
> Fix traceback error on missing embed

- cogs/README.md
- cogs/base.py
- cogs/info/cog.py
- cogs/info/features.py
- cogs/info/messages_cz.py
- config/app_config.py
- config/config.template.toml
- permissions/room_check.py
info: remove requests, use global session
Added command NASA daily image and task to send daily to space room (if it is big spam we can change it to thread later)
urban_embeds moved to features.py
none
> info: remove requests, use global session

- cogs/base.py
- cogs/moderation/cog.py
- cogs/moderation/messages_cz.py
- config/app_config.py
- config/config.template.toml
- database/db_migrations.py
- database/moderation.py
Add logging of kicks and (un)bans. This will log kicks and bans to channel and database. Will prevent re-verifying kicked/banned users because they changed their profile/name/nickname.
none
> Moderation logging

- cogs/moderation/cog.py
- cogs/moderation/features.py
- cogs/moderation/messages_cz.py
Fix checking for all servers with moderation. Check for only main guild.
Fix autocomplete in /slowmode_set
None
> Moderation cog

- cogs/report/views.py
*Sigh Here we go again.*
Making the attachments none makes the attachment disappear forever.
none
> fix: report missing attachment

- cogs/fitwide/cog.py
- database/verification.py
> Fix get_all_persons and update_db unused argument

- features/verification.py
- features/verify_helper.py
Verification for external employees
No issues yet
> fix(verify): external employees

- cogs/fitwide/cog.py
- features/error.py
fix using deleted webhook for long running commands which throw error
none
> fix: using deleted webhook

- cogs/fitwide/cog.py
- cogs/fitwide/messages_cz.py
- features/error.py
> fix: error.py dead webhook + restore update from login

- features/verify_helper.py
> fix: relation faculty

- cogs/fitwide/cog.py
- database/verification.py
- features/verify_helper.py
- fix percentage print
- ignore muni people on db update
- use global session for better pooling of requests
none
> fix: ignore muni people, use global session

- cogs/verify/views_verify.py
- features/verification.py
This should fix an issue that we saw recently with the resend code not working and also a couple of missing awaits.
no issues reported
> fix(verify): fix missing defer and await

- cogs/fitwide/cog.py
- database/verification.py
- features/verify_helper.py
> Duplicate detection + don't give out 0BIT anymore

- cogs/fitwide/features.py
fix failing sort on objects that doesn't have compare
none
> fix: sorting on teacher update

- cogs/fitwide/features.py
- cogs/timeout/cog.py
fix renamed room in verify
fix inverted condition
none
> Verify and selftimeout

- cogs/fitwide/messages_cz.py
> Update db single bugfix

- cogs/fitwide/cog.py
> Fix update_db_single naming and remove logging

- cogs/roles/cog.py
- config/app_config.py
- config/config.template.toml
- features/verification.py
> feat: Autoassign role on join

- cogs/roles/cog.py
> hotfix: guild id

- features/verification.py
> fix: newbie removal (for sure i swear)

- cogs/verify/cog.py
- cogs/verify/features_dynamic_verify.py
> remove newbie role on `Verify host` and dynamic verify

- cogs/README.md
- cogs/roles/cog.py
- cogs/roles/messages_cz.py
New command to move categories. This could potentially fix the hassle of random rearrangement of rooms when doing it with GUI.
None
> feat:create move_category command

- README.md
It is now obsolete and there is no point of maintaining it in the present
> Remove local setup from README

- cogs/verify/messages_cz.py
> typo in a command description

- cogs/timeout/features.py
Fix sending delete request to Grillbot API side.
none
> fix: grillbot send delete timeout

- utils/checks.py
fix false positive exception when using role privileged commands
> fix: false positive role exception

- cogs/latex/cog.py
- cogs/latex/messages_cz.py
- features/error.py
Latex command was updated to work with new API design of the website.
None
> fix: latex API changed

- cogs/latex/cog.py
Update font size and font family
none
> fix: update LaTeX font settings

- features/verification.py
Adds an accent to one of the faculty names so that it matches the current API.
Resolves https://github.com/vutfitdiscord/rubbergod/issues/1151
> Verification: fix USI faculty name unicode

- cogs/exams/features.py
Exam URL was changed
Not reported yet
> fix(exams): Fix link for exam server

- requirements.txt
Pillow version 11.1.0 and higher fixes our problem with generating of gifs https://github.com/python-pillow/Pillow/pull/8494
> update pillow lib

- cogs/README.md
- cogs/fun/cog.py
- cogs/fun/features.py
- cogs/fun/messages_cz.py
Add `/xkcd` command. 
Possible uses
- Random xkcd comic
- Specific comic
- Latest comic
None
> Add Xkcd command

- setup/leakcheck/leakcheck
> fix(ios): `leakcheck` hostname resolution

- setup/ssh_keygen.sh
> fix(ssh): trust host key on first connection

- .github/workflows/deployment.yml
- config/config.template.toml
- database/README.md
Update workflow and documentation
None
> Update workflow and documentation

- .github/workflows/deployment.yml
> chore: update deployment script

- cogs/prometheus/cog.py
- cogs/prometheus/grafana_dashboard.json
Interactions can be in DMs.
None
> fix guild is None

- cogs/verify/cog.py
Missing flag for guild visibility
none
> fix verify visibility in guild

- cogs/report/messages_cz.py
- cogs/report/modals.py
- config/app_config.py
- config/config.template.toml
- utils/user.py
> feat(report): add mention

- cogs/absolvent/cog.py
Xpath has changed, I also included some basic logging if there was failure while parsing the web for easier debugging.
> fix(absolvent): update xpath for thesis author

- features/verify_helper.py
Sometimes API returns the same mail multiple times which resulted in error when creating the dropdown as it should not contain repeating elements.
> fix(verify): Fix for repeating mail for VUT API

- cogs/autopin/cog.py
- Resolves #1239 
[Optional] Are there any post deployment tasks we need to perform?
> fix(autopin): handle situation when message is already pinned

- cogs/timeout/features.py
Update grillbot url and filtering for timeout get_user
- Resolves #1257
> Update grillbot url and filtering

- cogs/fitwide/cog.py
- cogs/roles/cog.py
- cogs/roles/messages_cz.py
Since it's unclear how we want to automate the creation of a "yearly role" lets just add a new command for now so we can do it manually and figure it out later ...
> Add copy_role command and remove 4bit-1mit role creation from increment_roles

- cogs/fitwide/messages_cz.py
> Add revert_role missing message

- cogs/fitwide/cog.py
> Add interaction defer to revert_roles

- cogs/fitwide/cog.py
- cogs/fitwide/messages_cz.py
Adds a vut_check command similar to mit_check and others
> Add vut_check command
