- config/config.template.py
- repository/reaction.py
Implements a karma ban that is used by giving a specific role to a user (ID is defined in the config, don't forget to change that), which disallows them from giving or taking away karma
> Implement karma ban

- config/config.template.py
- config/messages.py
- rubbergod.py
Allows specifying which rooms are okay for the bot, moves bot-room redirect message to config
Resolves #19
> Allow bot messages in rooms other than bot-room

- config/config.template.py
- rubbergod.py
After doing some testing, I found that `'uh oh' in message.lower()` is much faster than regex in most situations, here's some timings for 1.000.000 loops
```
string tested
'uh oh' in message.lower()
regex search 'uh oh' in message
regex match '^.*uh oh.*$' in message
```
```
'uh oh'
0.1317589
0.3485927
0.4204242
'uh oh '*100
0.3728719
0.3522985
0.6723283
'a'*500 + 'uh oh'
0.4225798
4.3999496
0.5864391
'a'*500 + 'uh oh' + 'a'*500
0.5828917
4.4007902
5.062168
'a'*1000
0.6251828
8.2081621
9.0072494
'xh oh ux oh uhxoh uh xh uh ox '*100
2.4949878
37.8629044
39.403863
```
> Make uhoh faster

- cogs/acl.py
- cogs/base.py
- cogs/fitwide.py
- cogs/karma.py
- cogs/meme.py
- cogs/random.py
- cogs/review.py
- cogs/room_check.py
- cogs/verify.py
- config/config.template.py
- config/messages.py
- features/acl.py
- features/karma.py
- features/reaction.py
- features/verification.py
- features/vote.py
- logic/rng.py
- logic/roll_dice.py
- repository/review_repo.py
- rubbergod.py
- utils.py
I noticed the a reoccuring pattern in the codebase where `Messages.template` was being called with `generate_mention(...)` to generate a response. My idea is we could instead create a template engine that will generate the mentions and fill templates automatically. This change is just a concept, I'd just like to ask if you think it is a good idea @Toaster192.
This simple "filler" utility is the first step towards a less chaotic template generation. It takes the attribute name of the template from `Messages` and automatically generates mentions with kwargs that are named `user` or `toaster`.
I currently have no way to test if the code works as I only have rubbergod set up on my other computer, so I might add some bugfixes later.
> WIP: Template engine concept

- cogs/fitwide.py
Adds a `.lower()` call to role names since they're lowercase in the config and uppercase in the discord server
> Fix role hoarder case sensitivity in role names

- README.md
- features/verification.py
Sometimes, deleting message in DMs results in 404 error, not just 403. Switching to broader HTTPException.
> Change exception

- cogs/karma.py
- cogs/review.py
- cogs/urban.py
- cogs/weather.py
- cogs/week.py
- features/karma.py
- utils.py
Fixes #181
Added helper/util function for this and applied it to all cogs that have already used author footer in some way - making it look the same across all these cogs. This helper also handles if the embed should have timestamp.
Additionally added to `?weather` 
Don't know which other cogs should use this feature as it's kinda hard to test this locally, mainly because of missing database data/exact discord setup or basically _out-of-FIT_ context (eg. `?ios`) - needs more production testing:))
You can keep this PR open and just comment what other cogs/commands should implement this and I will add it.
EDIT:
Notes about other cogs:
`karma` and  `review` - uses footer for pagination, reviews already take a lot of space so jamming author+icon before/after the pagination might still work
> Add author (and timestamp) into embed footers

- README.md
- docker-compose.yml
- requirements.txt
- rubbergod.py
As discord API has changed and looks like it requires intents to fetch some objects we have to update it or we will soon loose a lot of features.
Please note that updating application is required. Visit https://discord.com/developers/applications and in `Bot` card we need to enable `SERVER MEMBERS INTENT`. Adding this also to README so new users will be aware of this.
Updated README to include docs for discord application creation.
> Bump discord.py to 1.5, add intents

- cogs/warden.py
If user saw reaction from bot that his/hers post is classified as repost s/he could remove that image before bot sends embed message. After that embed message could stay here forever since original post was already removed. Sending embed before adding this reaction should fix this issue. Also deleting embed was not allowed when image was already deleted.
> Warden: reaction after embed

- cogs/urban.py
Wrong string was being shortened.
This error was already present in Amadeus, source of this cog.
> Fix urban cog error

- cogs/autopin.py
- cogs/base.py
- cogs/karma.py
- cogs/reactions.py
- cogs/review.py
- cogs/roles.py
- cogs/warden.py
- config/config.template.toml
Just idea to use one reaction handler, as Menus will be soon implemented this won't be necessary, but currently we are experiencing low reaction time due to lock operation on every call of on_raw_reaction function. Let me know how you (dis)like this temp fix. Currently I have tested just reviews, if we would like this idea I will take closer look at other cogs as well.
> use just one on_raw_reaction handler

- features/vote.py
A simple fix for this
Fixes #223
> fix `vote` wording, so that "11 hlasem" doesn't happen

- cogs/roles.py
It's useless create permission overwrites for users with Administrator permission. This users have acess everywhere by default.  It's also useless create overwrites for members who have access through the role.
For example: On VUT FIT server member with 1BIT role have access to IZP channel from role. It's useless create special overwrite for him.
> Do not create overwrites for administrators and users with access.

- cogs/random.py
looks like cog_command_error defined in discord.py does not catch all errors :thinking:
> fix error handler in random

- cogs/error.py
Sometimes there is error (especially in reviews) when message contains double quotes and bot responses just with general error and user doesn't know what is wrong. This should help user to identify errors in message.
> Notify user about double quotes error

- cogs/config.py
- cogs/studijni.py
- cogs/warden.py
- config/app_config.py
- config/config.template.toml
- config/messages.py
Also adding option to load missing values from template to config. Currently we are just loking into template if key is missing but we are not able to edit those values. PR should fix this issue.
> Warden ignore users in marking false positives

- cogs/help.py
As discord doesn't allow bots to exchange DMs, we need to send messages on server.
> [help] remove check for channel type

- cogs/help.py
- cogs/review.py
- repository/review_repo.py
[help] Migration to disnake caused a change in the Context object, so now bot and view are mandatory fields for object creation.
[review] Adding support for updating subject names, which includes flag if the course is opened this year, adding embed field that will notify user that this course is not opened.
> Fix help share and add warning about not opened courses

- cogs/fitwide.py
- cogs/random.py
- features/verification.py
- repository/database/verification.py
- repository/user_repo.py
This PR adds support for new format in passwd file. Users now have an email address in the year, which causes complications when importing new users.
Old format:
```
xloginXX:x:15693:251:Login that you dont know,FIT BIT 42r:/homes/eva/xl/xloginXX:/bin/ksh
```
New format:
```
xloginXX:x:15693:251:Login that you dont know,FIT BIT 42r mail=xloginXX@stud.fit.vutbr.cz:/homes/eva/xl/xloginXX:/bin/ksh
```
> Fixed merlin users processing

- buttons/embed.py
- cogs/help.py
- cogs/karma.py
- cogs/review.py
- cogs/streamlinks.py
- cogs/urban.py
- features/karma.py
This PR will allow us to better understand errors in interactions with reporting to our bot-dev channel. Also adding the on_timeout method for removing interactions after timeout to reduce confusion.
> add catch for interaction errors

- features/verification.py
This will actually send the same message twice because the first one is ephemeral. We need to end the deferred message and the second time to notify the admin about the missing login in DB.
Also removing unused logic folder
> Verify hotfix^4

- cogs/fitwide.py
- cogs/icons.py
- config/app_config.py
- config/config.template.toml
- config/messages.py
- repository/database/cooldown.py
- utils.py
Implements a slash command `/icon ui`, which allows any member to pick their role icon, which will show up next to their name
- Can be configured to only allow a given role icon to members with a certain role - see config.template.toml
- Can be configured to deny a given role icon if a member has a certain role
- Supports cooldown
> Add support for choosing custom icons

- cogs/help.py
Query:
```json
{
"method": "Help",
"parameters": {
"command": "slash_commands"
}
}
```
response:
```json
["urban", "pocasi", "icon", "svatek", "karma", "diplom_help", "cogs", "verify", "wtf", "meniny", "flip", "review", "channel", "roll", "tierboard", "diplom", "dynamic_verify", "week", "pet"]
```
> Add slash_command names to grillbot api

- cogs/meme.py
**Issue:** Whenever anyone on the server types `??` as a 'WTF' reaction, the bot treats it like a normal command and sends `Messages.no_such_command`.
**Fix:** Add `??` as a command that doesn't do anything.
Thx to @solumath for working proposal
> Fix: Treat '??' as a normal message, not a command

- buttons/review.py
- cogs/absolvent.py
- cogs/exams.py
- cogs/fit_room.py
- cogs/icons.py
- cogs/karma.py
- cogs/name_day.py
- cogs/review.py
- cogs/roles.py
- cogs/streamlinks.py
- cogs/studijni.py
- cogs/urban.py
- cogs/weather.py
- config/messages.py
- features/verification.py
Convert both user and admin commands in the exams cog to slash commands.
This PR also includes the following:
- defer reviews get
- rename `edit_original_message` to `edit_original_response` as this was renamed in Disnake 2.6, see docs: https://docs.disnake.dev/en/stable/api.html#disnake.Interaction.edit_original_response
`Changed in version 2.6: This function was renamed from edit_original_message.`
> Exam as slash commands

- cogs/vote.py
- config/messages.py
- features/karma.py
- requirements.txt
Add catch for unknown emoji from different servers -> applicable for nitro users.
Users will be notified on the first unknown emoji, and the rest of the message will be ignored.
Found a deprecation in `emoji` lib with our implementation -> updating requirement and implementation.
> Vote unknown emoji

- cogs/roles.py
- utils.py
group list outputs groups now in single message or cuts it in multiple if necessary
group add didn't have check for adding group with same name, now fixed
fix #460
> change output of "group list", "group add" check if group already exists

- features/bookmark.py
when using mention of channel users who don't see the channel have name "no-access" instead of actual name room
> fix discord no-access fuckup

- config/config.template.toml
Remove `name_day` from config template so new forks won't trigger GrillBot API by default.
> Don't load `name_day` cog by default

- .devcontainer/devcontainer.json
- README.md
- docker-compose.yml
This should allow users to develop in containers easily by just clicking on one button in vscode.
> Add dev container config and instructions

- cogs/karma.py
Karma commands do not always call the `botroom_check` at the same time. 
This commit aims to fix it.
> `karma`: Do `botroom_check` always at the same time

- cogs/fitwide.py
- cogs/grillbot_api.py
- cogs/name_day.py
- cogs/verify.py
- config/app_config.py
- config/config.template.toml
remove rolehoarders command which doesn't work because of missing config and no longer usable as we switched to less roles managing
get bot owner different way, user command for guild only
> remove rolehoarders command, get bot_owner

- cogs/README.md
- cogs/timeout.py
- config/messages.py
- repository/database/timeout.py
- repository/timeout_repo.py
`/selftimeout` [#484](https://github.com/Toaster192/rubbergod/issues/484)
> Selftimeout

- config/messages.py
grillbot.cloud is deprecated and moved to grillbot.eu
None
> replace grillbot.cloud to grillbot.eu

- buttons/review.py
- cogs/review.py
- config/messages.py
- features/review.py
Use grades A-F instead of confusing tiers 0-4, this should improve UX for users. I have also moved most of the Czech review texts to Messages.
> feat(reviews): convert tiers to grades

- cogs/memerepost.py
- config/messages.py
- utils.py
- [#] Bug Fix
Images with spoiler flag cant be in embed because then they lose the spoiler, instead they are sent as other_attachment
> bug(memerepost): Spoiler images can't be in embed

- cogs/README.md
- cogs/review.py
- config/messages.py
- database/__init__.py
- features/review.py
This PR fixes issue with updating subjects where sometimes wrong year/semester was assigned to subject. It was caused by change on the page where we are getting information about courses. Now I have added a check which is using table heading to parse year and semester information.
To enable removing old not correct data I have added a new parameter, that basically updates all subject in place. To update everything properly we need to first run with append argument set to false and then we can run it with True. This should not be needed in future but generally can help to avoid such issues as this one.
Also I took an opportunity to simplify the logic a bit and rework to slash command.
> fix(review): subject update command fix

- cogs/meme.py
- config/app_config.py
- config/config.template.toml
- config/messages.py
The "Upgraded pocitani" thread in free for all forum channel is about resetting when a mistake happens and some people "cheat" by deleting their message.
This PR makes the bot automatically send "1" to the thread whenever anyone deletes any message.
- Closes #608
Note: although changing the config is not needed - new config option gets loaded on restart from the template instead - it is maybe desirable to keep `config.toml` up to date as much as we can?
> Catch deleted messages in "Upgraded pocitani" thread

- buttons/embed.py
- database/review.py
- features/review.py
The average tier was not working because of 'GROUP BY' which resulted in SQL running AVG function per group (per review). I have moved the logic to python code instead. We are getting all reviews regardless, so I think it does not matter if you do the average on python or SQL level. I have not found a way how to do it in the same query.
I have also added a ignore for the constant error in adding buttons. I am still not able to reproduce it locally, so let's see what happens. Maybe we should remove the buttons in case of a error?
Closes #600
> Review avg tier fix

- cogs/icons.py
This PR adds emoji preview to the /icon command select. It also adds emoji to the textual confirmation interaction response.
> `/icon` Emoji preview

- buttons/embed.py
- buttons/review.py
Currently, buttons are removed when they are not relevant, e.g. review has no text pages. This PR will change this behavior to disable them instead of removing. Buttons are added when they are needed for the first time. I hope this will help to resolve the issues that we are seeing in this cog.
None
> fix(reviews): disable buttons instead of removing if not needed

- cogs/streamlinks.py
Fix datetime string parsing in `/streamlinks` command
None
> Use iso format when parsing streamlinks date

- buttons/bookmark.py
- buttons/report.py
- cogs/bookmark.py
- config/messages.py
- features/report.py
- modals/report.py
- utils.py
fix tags edit on report posts when sometimes because of asynchronous actions the post would have multiple tags applied
add files/images to report so we can see preview of whole message
none
> use edit thread for changing tags, add images/fiels to report

- cogs/absolvent.py
- config/messages.py
when user would call `/diplom` command and wasn't in verify db it would raise exception.
- resolves #713
> fix `/diplom` command when user is not in verify db

- rubbergod.py
forgot that old buttons wont be able to remove bookmarks because of their unique id so i put it back
none
> add bookmark:delete custom_id

- cogs/README.md
- cogs/base.py
- cogs/emoji.py
- config/config.template.toml
- config/messages.py
For now only for getting emojis and stickers from the VUT server. Versioning might be possible later. I don't think it's worth right now. Open to discussion if we want to have the zip updated everytime emojis change migth be counter productive if there was a problem with server but i think it can be enough just pinning the zip in channel.
- Related Issue #503
> Add download of emojis and stickers

- cogs/autopin.py
As described in #734 , `/pin get_all` could, under certain conditions, leak pins in private channels. This PR fixes the problem by making `/pin get_all` always ephemeral (only visible to the caller).
- Resolves #734
> Make `/pin get_all` always ephemeral

- docker-compose.yml
With before the maximum retries meant all of the time now in specific window, so shutting down the bot 3 times would result in one of us going to server and running it again. This should make more usable as it will try running it for 60s if it fails don't continue.
> compose rework

- cogs/fun.py
- config/messages.py
- features/error.py
- permissions/custom_errors.py
we encountered that page sometimes returned malfunction URLs. Now it should instead retrieve image and send it so it stays or returns error that API is broken.
- Resolves #738
> animal commands return file instead of url

- cogs/contestvote.py
- config/messages.py
- features/error.py
error handling didnt catch subcommands
printing of top contributions was missing the typing hint which was neccessary
> fix print of top contributions, add subcommands to error handling

- buttons/report.py
- config/messages.py
- features/report.py
deleted message in report system is now embed and user is able to resolve after the message is deleted
> rework delete message in report

- Dockerfile
sometimes it appears that the docker is missing graphviz. I don't know why or when but it happened to me and @Misha12 in past. With this it should be fixed for the future.
None
> add graphviz to docker dependency

- database/verification.py
- features/verification.py
Before this fix, it was somehow possible for a user to be multiple times in a DB, which resulted in DB exception. TBH I am still not sure how they could end up in such a state, but I would guess that they double-clicked on a button because it was seemingly unresponsive or they have already been on the server and some mod linked their account.
- Closes #797
> fix: Make sure that the user is only once in Permit table

- buttons/embed.py
Adding an option to automatically add a footer with the page number (e.g.: 2/4) in EmbedView by simply adding a `show_page=True` argument when initialising the class.
> feat(EmbedView): add option show page numbers in embed footer

- cogs/autopin.py
- cogs/streamlinks.py
- features/presence.py
As recommended here https://docs.python.org/3/library/datetime.html#datetime.datetime.utcnow
datetime.utcnow() will be deprecated in future versions
None
> fix: datetime.utcnow() deprecated

- config/app_config.py
- config/config.template.toml
- config/messages.py
- features/verification.py
- features/verify_helper.py
Add call to the new VUT API during verification. This will allow us to have more reliable data and also improve other parts of bot based on this API. I haven't completely removed old parsing to keep the compatibility layer for some time. When we verify this works reliable enough we will remove old way of fetching logins. The new approach is using on demand fetch per user.
> feat(verify): use new API for verification

- features/list_message_sender.py
`send_list_of_messages()` didn't work in some channel types (threads, for example). This PR should fix it
as it allows any `Messageable` as a destination.
> Fix list of messages not working in threads

- cogs/meme/__init__.py
- cogs/meme/cog.py
- cogs/meme/messages_cz.py
- config/messages.py
> migrate meme to folder

- cogs/dynamicconfig/__init__.py
- cogs/dynamicconfig/cog.py
- cogs/dynamicconfig/messages_cz.py
- config/app_config.py
- config/messages.py
> Migrate Dynamicconfig to folder

- cogs/ios/__init__.py
- cogs/ios/cog.py
- cogs/ios/features.py
- cogs/ios/messages_cz.py
- config/messages.py
> Migrate IOS to folder

- cogs/autopin/cog.py
- cogs/autopin/features.py
Mypy fixes in autopin
- Related #952
> Mypy autopin

- cogs/dynamicconfig/cog.py
> Mypy dynamicconfig

- cogs/contestvote/features.py
> mypy fix:contestvote

- .pre-commit-config.yaml
Now that we have all mypy issues fixed we can enable the pre-commit check again to run on all files.
- Closes #952
> ci: enable mypy in pre-commit ci

- features/verification.py
wrong import for verification file in features
none
> fix verify import messages

- cogs/README.md
- cogs/emoji/cog.py
- cogs/emoji/messages_cz.py
Rename emoji commands to simpler version. They were a lot similar and people got confused.
none
> rename emoji commands

- cogs/system/views.py
- cogs/warden/cog.py
- database/db_migrations.py
- features/error.py
- features/logger.py
- rubbergod.py
- Rewrite rubbergod.py to be subclass of `commands.Bot` which will be needed in future and is better for us
- add logging to bot which is better than print (also colors in terminal :rainbow:)
None
> rubbergod.py refactor

- .github/workflows/main.yml
- cache key hashFiles was changed to `pre-commit-config.yaml` because it's the only file that determines what is installed in cache, `requirements*` on the other hand have no effect on `lint` workflow.
Resolves #541
> feat: Cache `pre-commit` environment

- buttons/error.py
making interaction from buttons ephemeral does not make message ephemeral -> hence it's useless and needs to be with sending instead of defer
none
> traceback not ephemeral

- cogs/random/cog.py
remove mention in /pick command. It's unnecessary when the command implicitly tags the user, just makes it confusing when inputting user tags.
none
> remove mention in pick

- cogs/gif/cog.py
- cogs/gif/messages_cz.py
wrong use of getting user profile picture made the command blocking with using requests. Now fixed
none
> remove blocking requests in gif.py

- config/app_config.py
Fix the exception that the config class has no attribute instance. I tried to delete the attribute in the instance instead of deleting it from the class itself.
Closes #1047
> fix: config singleton pattern deletion

- cogs/timeout/features.py
when using `/remove timeout` on selftimeouted user, the update goes to grillbot which should not happen.
None
> fix sending update to grillbot on selftimeout

- features/verify_helper.py
Fix for new students who tried to verify before they were in DB. API didn't find them so the bot went to fallback with MUNI login. This is now causing issues because they are already in the DB with MUNI year, which is not correct. This fix should update the year if it has changed compared to the already saved version. Please note that this was not tested.
No GH issue
> fix: update year of users that are already in DB

- cogs/bookmark/features.py
- cogs/bookmark/messages_cz.py
Lottie sticker can't be converted into a file so instead it's ignored and a note is added to the embed.
- Resolves #777
> fix lottie sticker bookmark

- cogs/report/features.py
- cogs/report/views.py
Fix duplicating embedded image on report post (prob discord fault but is fixable with `attachments=None`)
Fix exception when removing the message in the deleted thread/channel (the message was cached).
Some nitpicks around types.
- Resolves #1084
> Report delete button traceback

- buttons/embed.py
- cogs/bettermeme/cog.py
- cogs/exams/features.py
- cogs/help/cog.py
- cogs/hugs/cog.py
- cogs/info/cog.py
- cogs/karma/cog.py
- cogs/review/cog.py
- cogs/review/views.py
- cogs/streamlinks/cog.py
- cogs/timeout/cog.py
Refactor ReviewView and PaginationView (old EmbedView)
These changes bring:
1. Using callbacks for buttons 
2. Using interaction check only for what it should be used (checking permissions for interaction)
3. Should resolve unpredictable errors with adding buttons to full row these errors were most likely associated with
- improper handling of interactions in `interaction_check`
- setting custom_id for not persistent buttons
- obfuscated adding of buttons which could have been fired multiple times since there could be 2 views that were listening for 1 message
4. We can template the PaginationView to other views more freely. We can't make them persistent though.
None
Buttons ⬆️ ⬇️ are removed instead of disabled. We could make them disabled too but I would prefer them staying all the time …
> Review refactor | Part 2

- cogs/system/cog.py
- cogs/system/messages_cz.py
Add a list of commands that have some conditions for calling. This is useful when we change commands and the integration of the command is changed in Discord (can only be edited manually by the administrator)
This works only on registered commands (loaded cogs).
- Resolves #706
> Command checks

- cogs/subscriptions/cog.py
Autocomplete can't give suggestions when there's no channel selected hence raising an exception on empty list.
none
> Subscription

- cogs/moderation/cog.py
This was added recently (https://github.com/vutfitdiscord/rubbergod/pull/1103) and it is causing issues, because defer is already called in the parent command.
> fix(moderation): fix slowmode command calling defer twice

- cogs/verify/cog.py
- cogs/verify/messages_cz.py
- features/verification.py
This should resolve the confusion for people who are not yet available in the API or have other reasons for not being recognized and it should also remove randomly sending emails to MUNI.
Dynamic verification is kinda of tricky, not sure where I should put it, so I kept it for both options to avoid confusion.
> feat(verify): split verification for VUT and MUNI into separate commands

- .github/workflows/deployment.yml
- init.sh
Implement deployment mutex to prevent deadlock and other race conditions when multiple deployments are in progress. Uses `lockfile` cmd from `procmail` because it seems to be the most robust solution available. The command is already installed on production, so there is no need to do anything else.
Resolves #1145
> feat,chore: Add deployment mutex

- cogs/dynamicconfig/cog.py
- cogs/fitwide/cog.py
- cogs/ios/cog.py
- cogs/karma/cog.py
- cogs/review/cog.py
- cogs/system/cog.py
- cogs/system/views.py
- cogs/warden/cog.py
- permissions/permission_check.py
Instead of passing our check to command.check we can supply it ourselves. This will be useful for other commands where we can precisely tell the error instead of generic command.check fail error. 
- Related Issue #1126
> feat: make is_bot_admin into command_check itself

- cogs/system/cog.py
- database/db_migrations.py
- database/error.py
- features/error.py
Small changes around handling setting dates in error log table
The introduced problem was created by using merge method on empty table. This will auto create rows if they do not exist. Hence we don't need to check if they exist, because they always must be there.
none
> Autocreate error log table

- .github/workflows/deployment.yml
Add workflow to prevent deployment. When PR has label "no-deployment" it will not trigger deployment workflows.
None
None
> update github actions for no deployment

- .github/workflows/deployment.yml
Fix check deployment workflow. The variables in Github Actions are not types but string, fromJson makes them parses them to type which can be negated.
None
> fix: correct deployment output parsing in workflow

- cogs/meme/messages_cz.py
Just changing the link that gets sent when someone messages `PR` to the current one (https://github.com/vutfitdiscord/rubbergod/pulls), instead of old Toaster192 repo.
None
> change repo link to current one in PR message

- .gitignore
- cogs/emoji/cog.py
- init.sh
- utils/constants.py
`/emoji all` raises an error because of the maximum file size. Emojis are now only downloadable in guilds, and support for multiple servers is in place.
None
> Downloading emojis raising error

- cogs/streamlinks/cog.py
`/streamlinks list` & `/streamlinks get` do not escape member names properly, so characters like _ can be treated as markdown syntax which breaks the listing. This PR adds character escaping to the appropriate listings.
Fixes #1143
> fix(streamlinks): escape member name

- cogs/verify/cog.py
Disnake changed dm_permission to contexts parameter.
None
> fix deprecation dm_permission

- docker-compose.yml
as pointed out by the newer version of `docker compose`:
```
WARN[0000] mount of type `volume` should not define `bind` option
```
> fix(compose): remove `bind` option from `volume`

- cogs/README.md
- cogs/prometheus/LICENSE
- cogs/prometheus/README.md
- cogs/prometheus/__init__.py
- cogs/prometheus/cog.py
- cogs/prometheus/features.py
- cogs/prometheus/grafana_dashboard.json
- config/config.template.toml
- docker-compose.yml
- features/logger.py
- init.sh
- requirements.txt
Add a Grafana dashboard with stats about our bot. Mostly, this will be command count, latency, uptime, guilds, users, etc.
Dashboard and Prometheus config must be applied with this PR merged.
Missing details:
- Currently supports command use only after the last reboot. Even though we can't command use persistent to boot this will be good insight for us. Might be resolved later.
None
> Add Prometheus logging

- cogs/info/features.py
Sometimes the API doesn't have URL even though it should have. This will at least send the text and not return error.
None
> fix None for missing url when NASA API breaks
